### PR TITLE
fix rman catalog support in oradb_rman

### PR DESCRIPTION
**Pull request by bartowl**
This PR fixes the RMAN Catalog part of `oradb_rman` role, which previously was not working at all due to for example missing sqlnet.ora.j2 template file.
It also cleans the code significantly and includes oracle wallet tasks only when needed, with expected idempotence.

As for now the only unhandled situation still is - when rman catalog is accessible, yet the database is not registered in the catalog. This will cause all backups using `rman_backup.sh` to fail. This circumstance should however not occure, and if so, it is easy to repair by just registering the database in catalog...

### CODE REVIEW

**Comment by bartowl** [comment]
Personally I do not like the fact, that `rman_password` is part of `oracle_databases` as it is very often looped over, and discloses this password even without asking... Is there something against to use `dbpasswords[rman_tnsalias][rman_user]` instead?? This could be an easy fix, that would stay backward compatible yet provide a bit more secure approach...

**Comment by bartowl** [comment]
Please do not merge yet, just found a bug in this implementation... will force push in a moment including better password handling...

**Comment by bartowl** [comment]
Now the code supports both: `rman_password` at `oracle_databases` and `dbpasswords[rman_tnsalias][rman_user]` and issues a warning if using `rman_password`. In addition a small bug in when condition at createCredential has been fixed, as listCredential output is a list due to the loop. Now should work as expected and is ready for merge.

**Comment by Rendanic** [comment]
Closing as duplicate of https://github.com/oravirt/ansible-oracle/pull/278

**Pull request closed without merging**
